name: .NET Core CI

on: [push]

jobs:
  build:
    name: Test ${{ matrix.os }} for dotnet ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         dotnet: [2.1.802, 3.0.100]
         os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet ${{ matrix.dotnet }}
      run: dotnet build
    - name: Test with xUnit
      run: dotnet xunit -nobuild 
